### PR TITLE
Add OpenGraph and Twitter cards statically

### LINKED ISSUE #223: Meta Tags, OpenGraph and Twitter Cards
Related to https://github.com/ponylang/pony-tutorial/issues/546

This could be implemented statically into [static/web.html](https://github.com/ponylang/pony-playground/blob/main/static/web.html) at first, but it would make sense to prospectively make it dynamic by [converting it to a template](https://woile.dev/posts/web-app-with-template-in-rust/) and [creating the tags depending on the `Query` params](https://docs.rs/axum/latest/axum/extract/struct.Query.html).

* snippet file name?
* [preview image of `snippet`, `code`, or `gist`](https://github.com/mplewis/src2png)
* extract [docstring](https://github.com/ponylang/ponyc/blob/main/STYLE_GUIDE.md#documentation)s from snippets and gists as description (could technically even be interpreted as frontmatter to support more than just the description)

_I know, I'm crazy, but one should be allowed to dream every once in a while 😉_

### PR DESCRIPTION
**Pull request by shaedrich**
Fix #223

### CODE REVIEW

**Comment by jemc** [comment]
I prefer this simple approach over the one in PR #228.

I don't think we get much value from the dynamic titles/descriptions pulled from the tutorial.

**Comment by shaedrich** [comment]
Too bad, but I can't say, I didn't expect that.

However, the OpenGraph data will be a bit misleading then. We essentially wrongfully tell the people, getting the link preview, that they will get an "empty" playground editor and conceal the fact, that it will be prefilled with what is send along in the URL making this essentially a distinct page 🤷🏻

**Comment by jemc** [comment]
> We essentially wrongfully tell the people, getting the link preview, that they will get an "empty" playground editor and conceal the fact, that it will be prefilled

Nothing about the description you wrote says or even implies that the editor they get to will be initially empty. So I don't think this is a problem in practice.

Let's merge it. :+1:

**Comment by shaedrich** [comment]
> Nothing about the description you wrote says or even implies that the editor they get to will be initially empty.

Not explicitly, but implicitly as this is quite common.

**Pull request merged**
